### ISSUE TITLE
Fix Lanyrd History

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#10]
it has no POST api

**Comment by ifraixedes** [comment]
For me Lanyrd is so ugly, then we could drop it; however if some people discover the LNUG events through it, we should have to keep it.

Do we know what are the sites that LNUG audience often use to keep updated?

**Comment by fmsf** [comment]
We could do a pool in the next meetup, its safer to ask than to guess. Or you can keep lanyrd as an auxiliar, more manual step.

**Comment by ifraixedes** [comment]
I think that the poll is good, at the end the audience are our clients. Doing manually is not that bad if it's worthwhile, otherwise from my point of view, I would dropped it.

**Comment by fmsf** [comment]
Y, a simple raise of hands should be enough, then we can extrapolate it.

**Comment by orliesaurus** [comment]
We can build it a POST API with PhantomJS, or something, who wants to help?

**Comment by ifraixedes** [comment]
@orliesaurus what you mean specifically for @lnug or in the scope of @gitevents?

**Comment by orliesaurus** [comment]
yes @ifraixedes Correct me if i am wrong but you can use phantomjs to perform complicated manipulations of the DOM ? so we can automate login and creation of new events?

**Comment by iancrowther** [comment]
@orliesaurus yes we *could* do that...

We should see if there is much SEO benefit to it first.. evaluate its worth a little and then decide on a course of action

**Comment by iancrowther** [comment]
analytics on the lnug home page and referer url's would be of more use right now

**Comment by orliesaurus** [comment]
What do you mean by referer's URLs? It's very hard to track incoming searches from google nowadays

**Comment by ifraixedes** [comment]
@orliesaurus PhantomJS is headless browser, so you are right, the issues may come if Lanyrd has any kind of protection for robots, depending of the protection the level of complexity and work to do would vary.

I don't know any about capchas, some people bypass them with not much problem, that it's the first and easy protection that Lanyrd may have.

On the other hand I faced with one site that it has a very strong anti robots (crawlers) protection, I abandoned the project when I faced that after I realised that the protection should be something related with mouse gestures because I used webdriver (totally a normal browser) and tested with different IPs and with timeouts between actions similar to the humans but I couldn't succeed.

My question was to ask if you were thinking to start the project as a subproject of @gitevents or not, than any technical, because in @gitevents there are several issues related with it, however they were all closed, then you may want to implement as independent project

**Comment by orliesaurus** [comment]
They can suck our balls, to be honest if they have protection versus scripted browsers they don't deserve our support.
I don't think they have captchas in Lanyrd.

**Comment by ifraixedes** [comment]
@orliesaurus you can see them straightaway on https://github.com/GitEvents/gitevents/issues?q=is%3Aissue+is%3Aclosed+lanyrd

**Comment by iancrowther** [comment]
@orliesaurus referer url = http://lnug.org?src=lanyrd

?src=lanyrd <- this is the referer bit

**Comment by orliesaurus** [comment]
@iancrowther  you can track those with google analtyics by default

**Comment by iancrowther** [comment]
I do believe so

**Comment by ifraixedes** [comment]
I was thinking in that, but I haven't used Google Analytics that much and with @orliesaurus [comment](https://github.com/lnug/feedback/issues/10#issuecomment-72102105) I thought that I was wrong thinking that it was too simple as that ;D

**Comment by orliesaurus** [comment]
FYI: https://support.google.com/analytics/answer/1033867?hl=en

**Comment by iancrowther** [comment]
+1

**Comment by sideshowcoder** [comment]
Just to throw that in here, I think a show of hands at the meetup is not that useful as those people already found the meetup so they are unlikely to use lanyrd again (honestly why would you ;)) so they are not a representative group in this case. From my own experience looking for meetups I know that lanyrd is a good place to find new ones, beside meetup.com. Analytics should tell more.

**Comment by iancrowther** [comment]
we were wondering about SEO!!

<img width="626" alt="screen shot 2015-09-22 at 20 45 30" src="https://cloud.githubusercontent.com/assets/76060/10029665/19d2dcb0-616b-11e5-976d-0248cbfe3b87.png">

**Comment by iancrowther** [comment]
https://github.com/lnug/feedback/issues/59
