### ISSUE TITLE
Increase diversity in our speaker line up

### ISSUE THREAD

**Issue by admataz** [lnug/feedback#107]
I have had anecdotal feedback - and twitter feedback, and it's just plainly obvious that the profiles of our archive of LNUG speakers is one-dimensional in terms of gender, and probably other measures of diversity too. 

I have been putting out generic calls for speakers regularly, and so far only men have responded - and even then, only just enough to fill our speaker availability each month.  

For starters - I think we should be putting specific effort to encourage more diversity, and particularly women from our community of developers, to give talks. If we could aim to have a women speaker for least one of our three speakers each month going forward  - that would be a start.  

@elischutze @claireinez @anniva @katebee @iteles @node-girls   - any thoughts, suggestions or actions we can take to rebalance this? because clearly this needs a new approach if we are going to change the pattern. 

anyone else from @lnug/contributors or @lnug/organisers  - let's get this conversation going.

**Comment by jkbits1** [comment]
@admataz good discussion. Definitely want to progress on this.

Still, over the last year we have had female and POC speakers, and female MCs. The speakers gave excellent talks, which were very well received. The audience is reasonably diverse. As meetups go, we do well.

Because of the wider issues with diversity in tech, it is hard to attract a diverse range of speakers (this is true for other meetups, too). I've been intrigued by the idea of group presentations, as it means that someone speaking isn't up there on their own. Any other ideas from anyone?

**Comment by sole** [comment]
Hi!

Excuse me for crashing into the discussion, but as someone who's a "minority" and has also been invited to many conferences on the basis of "being a minority", I feel like I know a bit or two about this :-)

(Disclaimer: I've been a couple times to LNUG so it's not a total *kool-aid-man convo-crash*, ok?)

**If you want to get people from minorities to speak on your event, you'll have to do outreach**. It's as simple as that. Putting an ad that says "hey, minorities welcome" on your site is nice to start with, but having the most previous speakers being white guys will send a message of "oh, yeah, we have a problem, but we'd like *you*, member of a minority, to fix this for us". So yes, you need to be encouraging, but you also need to do the hard work.

What this means is that **you're going to have to cultivate your networks and include more members of minorities on them so your network grows**. You're going to put a lot of energy on this. You're also going to be amazed when this works. And surprised and confused when people tell you to f*ck off—specially if you just approach them because they're a minority.

Why? Because **you *really* need to learn about them, not take the laziest approach**. What are they doing in their professional life? Why should they be speakers? What is it they work on that could provide a unique insight to the meetup? And no, the answer is **not** that they are a member of a minority.

This is going to take an awful amount of time. But it's the right thing to do. So—kudos to you for realising you have a problem! Well done! 🙌 

And now you need to start the work. Thankfully, the Internet exists and it can help you grow your network and educate yourself:

* If you don't know members of minorities, look at the websites of existing conferences or meetups. Look for minorities. See if any of them are in your area.  Maybe they are going to speak at a local meetup? Then attend it. Watch their talk. If not, watch their talks online. See if they would be a good match for your meetup. If so, make a note.
* While you're on that, also follow them on their blog/twitter/facebook/wherever it is they put their online presence. See what they talk about when they're not giving a talk. See who they talk to. Minorities tend to talk to minorities (although in their context, they might be the majorities). Learn. Don't interrupt. Listen an awful lot. Learn more. Maybe the thing they talked about in a meetup isn't even remotely as interesting as the other things they talk about normally with their friends. You'll find lots of things you don't understand if you are not friends with minorities already, so use your favourite search engine to find info about things that puzzle you. Don't ask minorities to educate you. Do your homework.
* If you don't know where to start, there are people on twitter compiling lists like "women in tech", "poc in tech", "lgbt in tech", and so on. Follow a list and also maybe thank the creator because they've done an amazing lot of work for you already.
* Once you know what these new interesting people do, it's the time to invite them!
* When you invite people don't tell them things like the following because you'll look so freakingly lazy that it'll be a miracle you get an answer:
  * "hi you're an awesome female/POC/minority developer can you give a talk at our meetup?"
  * "hi I saw you do node, can you talk about it in our meetup?"
  * etc
* Instead, tell them what you saw they talked/wrote about and why you're interested in hearing about it in your meetup. E.g.:
  * "hi, I saw your talk on doing art with node.js and I thought this could be a really interesting topic for our local node.js meetup"
  * "hi, we've been running a series of talks on modular frameworks and I thought your talk about frameworks could be a good conclusion to wrap the series"
  * etc...
* **Don't be fixated on the topic**. Make it clear that this is a suggestion, not a requirement. Sometimes people have ideas for a new talk and would love to try them out in a local meetup before submitting to a conference. Tell them you'd be open about this, it makes things more interesting and welcoming!
* If they say no, don't be offended. Members of minorities are also at a disadvantage when it comes to things such as free time, so attending a meetup to talk for free is a precious extravaganza few can afford. Some people can barely afford tube tickets!
* Also, don't ask them to get you in touch with more people of minorities, because they have better things to do than your own outreach work. If they do offer to do that spontaneously, thank them! Because that is a very nice and expensive gesture on their part.

The above is about people who already have spoken or have put their thoughts online and maybe have got the attention somehow. But you might also want to use your meetup to discover and catapult (not literally!) new speakers. One way to do this is to talk to people of minorities in the meetup, and get to know what they do. Oftentimes you'll realise that you have amazingly skilled attendees, but you never paid attention to them because your biases were blinding you. That woman sitting quietly in a corner? Not a recruiter--actually the head of development at an agency doing amazing 3D stuff on the browser. The POC nodding as the speaker's laptop crashes? Lead developer at a company that specialises in aggregating crash data. And so on.

Speaking to people of minorities at meetups without appearing like a total weirdo is quite hard it turns out. But you could start by bias-checking yourself, and doing simple things such as welcoming visitors if it's the first time they join you, introducing yourself, asking them "what do you do?" instead of starting with a bias-loaded question like "so, are you a designer?". And then make a mental note of that, don't force the conversation too much, and try to remember next time you see them. And build a network gradually. You don't want to freak people by interrogating them the first time you meet them, or they'll never go back.

The more varied and diverse your meetup is, the more attractive it will be for people from minorities.

Jed also wrote a very interesting guide about how they have grown their meetup to be welcoming and inclusive: https://github.com/jed/building-brooklynjs

Phew! This is a lot of text already and I have barely started. I hope it gives you some ideas. Also hope to be able to join the meetups some time this year! I'll be observing to see if you're putting this in practice ;)

**Comment by olizilla** [comment]
<3

**Comment by admataz** [comment]
hi @sole -  thank you for giving the time and thought to write this  - and really opening this discussion.  

I think these ideas can help us all at LNUG to start shaping our efforts. As you suggest, there's a lot more to be said - but this is a great start.

Going forward with this as a fairly informal organisation we need to appreciate that this may not be easy as we wish -  and it will take time and effort to achieve what I hope will be a real transformation.  I think a principled approach with genuine respect for individuals is key - and your words really express this in a helpful and practical way. 

Thank you! Please feel welcome to crash into the discussion/ action any time!

**Comment by orliesaurus** [comment]
Great reply @sole we did try different approaches in the past but this break down will definitely help us going forward! Muchas gracias :fist_right: :fist_left:
