### ISSUE TITLE
LNUG stickers - sponsors, designs (same old, or new?)

### ISSUE THREAD

**Issue by admataz** [lnug/feedback#108]
@lnug/organisers @lnug/contributors : 

We all love stickers. New organiser @MattJLeach has been looking into arranging some new stickers for LNUG...

> I’ve been looking into the LNUG stickers and found 2 designs on the Repo (https://github.com/lnug/resources/tree/master/stickers/official). Would it be an idea to get an updated design or would it be OK to use one of these 2 designs to start things off (I like the 2015 one). I’ve also got a sample pack from StickerApp (https://stickerapp.co.uk/stickers/) and they look good quality and cost £25 for 100 (25p each). What do you think?

It would be good to find a sponsor to pay for them directly so we don't have to deal with cash and transactions... Is anyone working somewhere that would be willing to put budget to this kind of thing in exchange for a big shout out from LNUG and a lot of love? Maybe 200 stickers to start?

Also, any feedback/ideas on the stickers, design etc or other materials  - please have your say here

and thanks for getting this moving @MattJLeach ! 🥇

**Comment by MattJLeach** [comment]
Hi @admataz 

If the plan is to sell the stickers at meetups in order to get some working funds for the group, I don't mind paying for them to start with. I could just recoup the cost from the first sales and then the rest goes to the group.

I'll bring the sample stickers that I got to the meetup tonight so you can look at the quality and then have a chat in the pub after about design. Would be nice to then have them ready for next months meetup.

Regards
Matt

**Comment by admataz** [comment]
hi @MattJLeach  - thanks for looking into this and providing the samples - today I ordered a batch of 200 - hopefully they arrive in time for our meetup next week

**Comment by iancrowther** [comment]
Hey @admataz 

I've got about 100 stickers still that I keep meaning to drop off.  I'll try and stop by the next event

**Comment by admataz** [comment]
oh cool! thanks. and it will be good to see you
