### ISSUE TITLE
Cider! Wine!

### ISSUE THREAD

**Issue by overlookmotel** [lnug/feedback#114]
This is a rather ridiculous thing to raise an issue about, but you asked for feedback on the beverage selection last night, so...

Would it be possible to get some cider? Personally, I find a drink helpful when entering a room full of strangers, but I dislike beer.

Also, I see that encouraging a wider diversity of attendees has been discussed quite a bit here. Having wine as an option might be appreciated by some. I'm not trying to trot out the tired old stereotype that women all like wine. All I mean is that beer and pizza projects a bit of a bloke-y image.

Just my two pennies worth, feel free to disregard...

**Comment by overlookmotel** [comment]
Related to #103.

**Comment by admataz** [comment]
good points, thank you. 

I stopped buying wine a couple years ago because no one drank the bottles I bought! they were often leftover at the end. I swapped them out for a few bottles of prosecco  - which seem to go down well - maybe I should try wine again or increase the prosecco count - but will also add some cider and see how that goes. Personally I don't like cider - so label recommendations accepted!  

I'm generally happy to support more diverse range of catering/drinks as much as possible - including non-alcoholic and diet specific food (not everyone likes or can eat pizza) - so as long as we can fit it into budget and practicality - keep the suggestions coming!

**Comment by overlookmotel** [comment]
@admataz Ah sorry please ignore me on the wine then - no point buying it if no-one drinks it.

Cider: Like beer, I guess people have different tastes. I'd say Aspalls or Stowford Press are probably safe bets - seem to be popular in pubs. Avoid Strongbow if you can - it's cheap, but pretty foul. But, beyond that, for me at least, I don't think the brand is that important - anything is better than the aberrant monstrosity that is beer!

Please don't take any of this as criticism. Of course it's great that free food and drink of *any* variety is provided - very generous of you and LNUG's sponsors. I only posted this because you asked for feedback.

**Comment by admataz** [comment]
@overlookmotel  - thanks! no offence taken at all  - will look to add some cider for next month's order - and not strongbow - which from your description can probably be blamed for why I don't like cider 😄

**Comment by admataz** [comment]
cider is now on the regular list
