### ISSUE TITLE
Move jobs to github

### ISSUE THREAD

**Issue by orliesaurus** [lnug/feedback#14]
I think we should adopt the same mechanism that we have for speaker applications on the job section.
I don't see why we need a password to allow job posting, having github-as-a-backend will allow us to edit/delete job ads that are not welcome.

Best,

**Comment by admataz** [comment]
To my understanding -  @andrew's initial idea behind the password that was only revealed at events,  was to ensure recruiters were attending the events, and as such were genuine members of the community. So it was less of a spam filter, and more of a community filter.

**Comment by orliesaurus** [comment]
Ok how many recruiters do you think will be "spamming" our job board if we use github as a backend?

**Comment by admataz** [comment]
Well the question is really, does the password help the event?. i.e. will people looking to hire node developers come to the events to talk to people  whether they need to get the password for the jobs board or not,  or will they just post jobs and would that still be ok?

**Comment by orliesaurus** [comment]
Idk, what do you think??

**Comment by iancrowther** [comment]
ok so im aware of a few.. we had 2 agencies at the last event

**Comment by admataz** [comment]
looking at our jobs board, we aren't exactly drowning in job posts - so I reckon you are right and it's worth bringing the technology together - and take it from there. I don't get the impression that many attendees are coming to the event because they have to get the password to post a vacancy they have.

**Comment by admataz** [comment]
oh - ok just as I posted my comment @iancrowther posts to the contrary :) Were they there for the password? Or do you think are they attending anyway because they want to meet potential candidates?

**Comment by iancrowther** [comment]
networking - we never gave out the password :-)

**Comment by admataz** [comment]
ok so in a long winded sort of way, @orliesaurus  - personally, I have no objection to your suggested enhancement. +1 !

**Comment by sideshowcoder** [comment]
Just my opinion but I feel there is no lack of general Job boards, but having one closely related to this community seems useful. Making it more general will probably get more jobs on it but I would be sure it increases the sum value of the jobs posted. I mean there is generally no shortage in jobs for node developers I feel, but the filtering is very bad in general so if it gets backed by github would it be possible to move to an approve model instead of delete if bad?

**Comment by orliesaurus** [comment]
Yup that's what I mean - we have more control over the posts, i.e. last few months there was .NET job advertised - lol and to delete it you had to go through the mongodb interface. pretty annoying if you ask me :(

**Comment by sideshowcoder** [comment]
Yeah that makes sense. In that case :+1

**Comment by ifraixedes** [comment]
It sounds like a plan; +1
