### ISSUE TITLE
SWAG

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#20]
What swag do you want?

**Comment by orliesaurus** [comment]
tshirts

**Comment by iancrowther** [comment]
t-spring.com? we can order a bunch and then let everyone purchase when we run out

**Comment by iancrowther** [comment]
any design suggestions?

**Comment by orliesaurus** [comment]
https://github.com/lnug/lnug.github.io/blob/master/assets/stickers/official/official_hex.png

**Comment by iancrowther** [comment]
we should add stickers to marketplaces such as....

https://www.stickermule.com/marketplace

**Comment by iancrowther** [comment]
socks anyone? http://swag.sockclub.com/

**Comment by iancrowther** [comment]
startupthreads.com

**Comment by timruffles** [comment]
socks!

**Comment by ifraixedes** [comment]
Socks!

**Comment by iancrowther** [comment]
ok socks it is! we need a logo sorting that we can upload..

@maxwellito?

**Comment by maxwellito** [comment]
Socks? You ask me to design socks? Mmmm... Is there any design
limitation/restrictions to respect?

**Comment by iancrowther** [comment]
no we just needs an upload able logo

**Comment by maxwellito** [comment]
I looked how it works. It's based on a pattern, maybe we could use the
opportunity to do something more fancy than just a logo on a pair of socks.
Tonight I'll try different designs (simple logo, pattern, and wtf).
I'll post them here

**Comment by maxwellito** [comment]
I have the LNUG logo in big size (transparent and with grey background)
But I couldn't use the simulator of SockClub, because it was repeating the logo.

![lnug logo grey](https://cloud.githubusercontent.com/assets/1097232/8071106/f07e3f4e-0efe-11e5-84f7-f4d4debe9ec7.png)
![lnug logo transparent](https://cloud.githubusercontent.com/assets/1097232/8071107/f07fa1ae-0efe-11e5-9a88-6ce863e7c2ba.png)

Then for fun

![screen shot 2015-06-09 at 22 46 40](https://cloud.githubusercontent.com/assets/1097232/8071129/1587a3de-0eff-11e5-8990-9222423a3769.png)

**Comment by iancrowther** [comment]
ha - love it

**Comment by iancrowther** [comment]
I have found someone who will do socks for us.  They will be arounf £15 per pair.

I can take orders

**Comment by iancrowther** [comment]
T-Shirts have been made

**Comment by iancrowther** [comment]
@alanshaw - how can people buy t's if they miss out on free
