### ISSUE TITLE
site calls to action

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#67]
we can relegate archive and discuss and promote newsletter and apply to speak

**Comment by iancrowther** [comment]
also we need to a link to "Sponsor Us"

**Comment by simonmcmanus** [comment]
I think we should probably leave discuss in the primary. 

Where should said sponsor link point?  

So far it's looking like this:

![screencapture-127-0-0-1-8080-1442045551544](https://cloud.githubusercontent.com/assets/55853/9830652/a8229b58-592e-11e5-925e-6855c8e7fae0.png)

Thoughts?

**Comment by iancrowther** [comment]
I would ideally like a seperate page outlining the different sponsoship packages

gold / silver / bronze

with clear calls to action

**Comment by iancrowther** [comment]
im not keen on the font dude, it now very nice to read

**Comment by iancrowther** [comment]
also the next event thing is using way to much screen real eastate.  it would be cool to emded a ti.to ticket form there

**Comment by iancrowther** [comment]
mail list is nice positioning

**Comment by web-bert** [comment]
Looks good, I quite like the ticket, but maybe the newsletter signup and ticket can share the same line (when space permits)?

**Comment by iancrowther** [comment]
Yeah rwd that sucker

**Comment by simonmcmanus** [comment]
@iancrowther  is it the heading font or the body font you don't like?

**Comment by simonmcmanus** [comment]
@iancrowther can you create the content as markdown files on github pls and let me know where they are located? Separate markdown files for each page. At first we can link to those pages, then I can pull them in using the build script.

**Comment by simonmcmanus** [comment]
this is just the desktop version, on a mobile version there is much less white space but my screen capture software keeps getting confused:

![screencapture-127-0-0-1-8080-1441975916932](https://cloud.githubusercontent.com/assets/55853/9835920/e88ac12c-59f9-11e5-83c1-c7c4610ad395.png)


I built it mobile first (there is only one breakpoint) so it will work on all devices, if we want to optimise/customise for desktops we can do that later.

**Comment by simonmcmanus** [comment]
i will have a play with the ticket/mailing list and see what I can come up with.

**Comment by iancrowther** [comment]
@simonmcmanus - fonts sorted :-)

**Comment by iancrowther** [comment]
yep - all over markdown files for the pages +1

**Comment by iancrowther** [comment]
@maxwellito @benbyford @web-bert 

could pitch into this discussion re: ti.to / ticket info & mail list

**Comment by benbyford** [comment]
what needs style decission?

**Comment by maxwellito** [comment]
To me the ti.to looks great. The only detail to change would be the space between the sponsors logos but I think somebody tried before and it wasn't possible.

**Comment by iancrowther** [comment]
@maxwellito @benbyford do see the screenshots in the thread above? That'd be the contect here chaps

**Comment by iancrowther** [comment]
this needs breaking down into smaller issues

**Comment by iancrowther** [comment]
@maxwellito - could you add your feedback pls

**Comment by simonmcmanus** [comment]
@maxwellito - yes pls. Those layouts were just based off feedback in the website repo. Keen to get more feedback before I start testing it across different browsers.

**Comment by maxwellito** [comment]
![photo-on-16-09-2015-at-19 52](https://cloud.githubusercontent.com/assets/1097232/10054837/2214f8f2-622b-11e5-8a15-115185902112.jpg)

This is what I was thinking. But it's just a point of view.

**Header**
A smaller logo, seriously, currently it take half of my screen.
On desktop it can be on the same line as the menu.
On mobile the menu item must be on a separated line but must stay inline, there's enough space and we don;t have a lot of items.

**Headline: the ticket**
I love the idea, but it take too much space too, and let the side completely empty. It can be more appealing.

**Newsletter**
The newsletter can be inline with the inputbox. (with a nicer design, something sober)

**The talks**
I would keep them as they are right now on the website, instead of using columns. Simply because talks doesn't have the same text description length and it can end up with a random look. While with the current design, it's less visible.

**Sponsors**
A two column sponsors should look nicer, atm there is too much space between items.
And keep the same size on mobile, just adapt the layout (simple float).

**Footer**
I like the one in the PR :smile:

**Comment by iancrowther** [comment]
@simonmcmanus was this useful?

**Comment by simonmcmanus** [comment]
very. thanks @maxwellito for the help with the redesign.
