### ISSUE TITLE
Hackday Guide

### ISSUE THREAD

**Issue by ifraixedes** [lnug/feedback#8]
@lnug with @opensauceit ran a hackday yesterday (17/01/2015), we are asking to the community some feedback about it to know if you are interested in attending more events like this.

Feedbacks can contains:
- Things that were good and to repeat in next events.
- Things that we missed, we should provide in the future events.
- Improvements.
- Suggestions.

Please, refrain from posting comments that only say "Thanks", etc., we are glad to receive those but it is not the right place for those.

On the other hand, feedback must be constructive as saying good or bad without any reason don't help, so we reserve the right to remove them, moreover whenever you can provide your solution idea if you have any.

Thanks so much.

**Comment by iancrowther** [comment]
My initial thoughts are to run the next event as a 2 day and spend the first morning on planning and analysis.  Although we had a solid vision, we simply had not thought about the details enough.

**Comment by ifraixedes** [comment]
@iancrowther good point, because if we don't want to burn out, the time period from 10 to 5 is good because it's weekend, however one day is difficult to get a lot done, you know, we catch up with people, we put the brains in the context and the project status and we start to hack, then one half day is gone, then having two days we should get 1.5 days coding.

**Comment by trevorah** [comment]
Having the barebones site pre-made by @orliesaurus was awesome as it really helped to solidify what we were doing. By this I mean we didnt need to have a long discussion over what people thought the site should look like etc.

Its hard to organise a distributed team, especially if the majority of them have never worked together in the past. And to get them working on the same repo? Thats crazy hard. 

One thing that worked is that we ended up finding an architecture that required as little cooperation as possible. It sounds counterintuitive for a lovely organisation such as @lnug to want such a thing, but it really cut down on what each person or small group had to worry about. This isnt something you would necessarily want to aim for with a long project, but as a singe day event, it works.

If you combine the "pre-made stuff" idea with the "minimal cooperation architecture" then perhaps next time someone should hash out an ultra basic version of the app. Something that people could fill the blanks in with their own node modules. I.E:

* instead of email notifications, just console.log something.
* show events on the website? just print out the raw github api response
* event metadata? nah, just take the plain text from the issue/milestone
* meetup integration? console.log

Then in the morning you show everyone the super ugly app, group people together based on experience etc, and send them out to solve one problem each.

What do you think?

**Comment by jkbits1** [comment]
@trevorah I like your suggestion. It really helps me if I can focus mainly on the code with a small group, especially with a tight timescale. Having a clear-cut target and not spending too much time on different teams discussing  the best approach sounds ideal.

**Comment by ifraixedes** [comment]
I agreed with @trevorah and @jkbits1 those suggestions apply for hackathons that we would like to run to a clear target which is not achievable during the hack time that obviously it was the case to create @GitEvents

@iancrowther was in the point to create a hackathon under that topic but after he gave the freedom to work in personal projects, I agree with that approach, and some people worked in @GitEvents and others in personal projects.

I think that the hackathon wanted to promote the project, kickstart it and get people interested in the collaboration, however in my opinion, project have to be organised after the rage to get more clear tasks and less integrations issues and give people guidelines to move in the same direction, but I also think that they are on the way.

From your appreciated feedback I can extract:
- Organise hackathons with an honest achievable target
- Make sure that people understand the basic "rules" of distributed teams with open governance, otherwise ask in advance to identify them and teach or give some tips

By the way @trevorah your i.e. sounds as a plan to take it.

Thanks guys!

**Comment by iancrowther** [comment]
all valid points.. 

keep it rolling in as it will make for a more professional experience in the future.. once again, your participation is greatly appreciated..

beer on the 28th anyone?

**Comment by iancrowther** [comment]
@lnug/organisers if you want some help automating some of your actions.. we can do a hackday.  just let meknow

**Comment by iancrowther** [comment]
It would be awesome for this to become a hackday-guide.md.  that way we can render it as a seperate page

**Comment by admataz** [comment]
some good discussion here - archiving
