### ISSUE TITLE
URGENT - newsletter patch

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#85]
We missed some sponsors

- YLD - Wrong Logo
- Nexttick - Missing, Again
- Braintree - Missing

**Comment by iancrowther** [comment]
@admataz can this get sorted as a priority?

**Comment by admataz** [comment]
ok - thanks @iancrowther  - I think we need a better way of communicating and confirming a month's sponsors - and also getting confirmation on proofread on the newsletter has all the required and accurate content before being sent - because once they're gone....  there's no getting them back from peoples' inboxes.

I always send a test mailer to the group before sending the mail to get some eyes on it - feedback is essential, as I'm it seems I only have half the required info sometimes... 

So looking at these points and omissions: Braintree wasn't on any of the issue lists as sponsors this month discussing the newsletter - if they are carried over from a previous month - they need to be included explicitly  - I'm not sure what agreements you have with sponsors, so better to spell it out.   And I thought  you wanted to take Nexttick off this month?  - isn't that what we discussed?  YLD logo - should have been picked up in tests - I wasn't aware of this difference. 

So... 
From now on - for each month I will create a new issues in planning and in feedback for the newsletter - one to gather internal content (sponsors, announcements, tests and approvals etc) and the other to get community news. 

I also think it's worth creating a new 'sponsors for [month]' issue for each month in planning - so there is a definitive list of who is contributing and needs recognition.

**Comment by jkbits1** [comment]
@admataz I agree with the principles underlying your comments :+1:

**Comment by iancrowther** [comment]
@admataz - am in agreement, will follow your lead here..

**Comment by simonmcmanus** [comment]
@admataz the above all sounds very sensible. 

For the site redesign Im going to need a json file/object which lists the sponsors for a given month, something like:

https://gist.github.com/simonmcmanus/227bc2904b578017d5a7

How about we add a sponsors.json file into this repo:

https://github.com/lnug/resources/

@iancrowther could maintain that list and we can all consume it. 

would that help @admataz @iancrowther ?

**Comment by iancrowther** [comment]
works for me.

@simonmcmanus - do you have a particular structure in mind?

**Comment by admataz** [comment]
as discussed with @iancrowther  - will send out a post -event email with all the sponsors included.

**Comment by admataz** [comment]
moving the above related conversation to https://github.com/lnug/planning/issues/79
